### ISSUE TITLE
info about mqtt dependency

### ISSUE THREAD

**Issue by dario-frongillo** [sclausen/ngx-mqtt#118]
- [ ] **I have searched for similar issues in this repository, but couldn't find one.**
- [ ] **I have read the README and have a basic understanding how angular works.**
## I'm submitting a...

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report  
- [ ] Feature request

## Current behavior
It is not a bug issue but only an info that i need: why you have declared mqtt.js as dev dependency and not as dependency ? i have seen that the lib use the browserified version. why the lib not use the npm dependency? 
thanks a lot

**Comment by sclausen** [comment]
I think your questions can be answered with two explanations:
1. `mqtt.js` was (I just removed it) a dev dependency and not a "normal" dependency, because the library once depended on its typings.
2. The npm version is currently not used, because a few angular versions ago the node-shims have been removed and `mqtt.js` didn't worked anymore by simply adding it as a dependency. Therefore I use the browserified version and bundle it into the library.
