### ISSUE TITLE
This library does not work with Angular 11

### ISSUE THREAD

**Issue by johnlewiskalahari** [sclausen/ngx-mqtt#170]
- [ ] **I have searched for similar issues in this repository, but couldn't find one.**
- [ ] **I have read the README and have a basic understanding how angular works.**
## I'm submitting a...

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report  
- [ ] Feature request

## Environment

<pre><code>
ngx-mqtt version: X.Y.Z

- Broker 

Others:

</code></pre>

**Comment by johnlewiskalahari** [comment]
Does not install due to webpack dependency issues, then complains about missing globals / buffers etc... which apparently means it has no been designed to work in a browser. Yet it is supposed to be for Angular....

**Comment by sclausen** [comment]
This library has been designed to work in the browser, but after many new angular versions they obviously changed something so this library breaks.
If you‘ve read the other issues, you should’ve seen that this is a known problem. Sorry, I didn‘t had enough spare time to provide a fix for this. If you just want to consume free libraries from people who made this in their spare time, you should search for another one which isn’t [sic] "a piece of shit" (renaming this issue doesn‘t change what you initially titled it)
I‘m closing this now because it’s already known and tracked and because you‘re plain impolite, indeed impertinent.

**Comment by sclausen** [comment]
It seems others can‘t see the original title, so to explain my resentment:
![6DD2278C-FF68-43B8-B554-5C13831138A0](https://user-images.githubusercontent.com/916076/99971784-f5176a80-2d9d-11eb-9382-0633133188c6.jpeg)
