### ISSUE TITLE
Support for Clean Session,  Will options

### ISSUE THREAD

**Issue by argupta23** [sclausen/ngx-mqtt#175]
- [**] **I have searched for similar issues in this repository, but couldn't find one.**
- [**] **I have read the README and have a basic understanding how angular works.**
## I'm submitting a...

- [x] Feature request

## Current behavior

Does the current implementation support "Clean Session and Will " as described in the standards?

## Expected behavior
It looks like mqtt.js does support it but I was not able to find anything in here.

Can you please confirm?

Thanks

**Comment by sclausen** [comment]
Since this is (just) a wrapper around mqtt.js with observable workflow, it is thus capable of will and the clean session flag. This library extends mqtt.js typings so if you use the according client options, you should not see any typing errors. Can you confirm using [the clean flag](https://github.com/mqttjs/MQTT.js/blob/37b12cb94737acddfe0fa016e013516ba3b9a031/types/lib/client-options.d.ts#L36) and [the will object](https://github.com/mqttjs/MQTT.js/blob/37b12cb94737acddfe0fa016e013516ba3b9a031/types/lib/client-options.d.ts#L75) on the client options work for you or do we have a bug situation here?
