### ISSUE TITLE
Problem with LAN connection

### ISSUE THREAD

**Issue by KrossTechMDA** [sclausen/ngx-mqtt#176]
Greetings.
I'm using ngx-mqtt on a project, and I'm trying to connect to the other machine (server) and I can't. I am using the following settings

app.module  - 

export const MQTT_SERVICE_OPTIONS: IMqttServiceOptions = {
  hostname: '192.168.0.4 ', ---- SERVER IP
  port: 9001,
  path: '/mqtt'
}

  imports: [
    MqttModule.forRoot(MQTT_SERVICE_OPTIONS)
  ],

I get the message on browser:

WebSocket connection to 'wss://192.168.0.7:1883/mqtt' failed: Error in connection establishment: net::ERR_CONNECTION_RESET

Can you help me?

Best Regards

**Comment by KrossTechMDA** [comment]
Duplicate of #

**Comment by sclausen** [comment]
If you have another issue with the library which may be a bug and can't find help here, please follow the issue template and provide a [minimal reproducable example](https://stackoverflow.com/help/minimal-reproducible-example).
Otherwise, I can highly recommend [stackoverflow](https://stackoverflow.com/) for asking questions.
