### ISSUE TITLE
publish last will message LWT

### ISSUE THREAD

**Issue by sebvie** [sclausen/ngx-mqtt#189]
I would like to implement a last will message:
https://stackoverflow.com/questions/17270863/mqtt-what-is-the-purpose-or-usage-of-last-will-testament

Instead of just closing the connection after a client has gone offline, LWT messages can be leveraged to define a message to be published by the broker on behalf of the client, since the client is offline and cannot publish anymore.

I did not find a method to do this with the librabry, could you help me with this?

Thank you very much for your great work on this library, it is helping a lot!

**Comment by sclausen** [comment]
There is no dedicated method for this. Since this is a (smart) wrapper around MQTT.js, the usage of last will is the same.
`IMqttServiceOptions` extends `IClientOptions`, which has the field `will` with the following fields: https://github.com/mqttjs/MQTT.js/blob/d8be59eba419d65ad2f46734623fd91ec437d6e2/types/lib/client-options.d.ts#L76
I hope this helps.

**Comment by sclausen** [comment]
I assume this helped.
