### ISSUE TITLE
How can i use dynamic username and password for mqtt Broker 

### ISSUE THREAD

**Issue by arihantdaga** [sclausen/ngx-mqtt#23]
Hi, Thanks for this library, it's really great. 
I wanted to use this in my ionic project, i saw the example provided, but the problem is i will get username and password from the api call after the app is initialized, so i cant' write this function in my AppModule. 

```
export const MQTT_SERVICE_OPTIONS = {
  hostname: 'localhost',
  port: 9001,
  path: '/mqtt'
};
......
MqttModule.forRoot({
      provide: MqttService,
      useFactory: mqttServiceFactory
    })
```
Can u suggest me how to do use it in my app, where lets say after user logs into the app, he'll recieve in api call mqtt username and password. And it'll connect to mqtt broker after that using those username and password. Thanks in advance.

**Comment by sclausen** [comment]
You could manually use `MqttService.connect(options)` if you set `connectOnCreate: false` in the `MQTT_SERVICE_OPTIONS`.

So something like this:

``` typescript
@Component({
  selector: 'mqtt-example',
  template: `
    …
  `
})
export class ExampleComponent {
  constructor(private _mqttService: MqttService) {
    _mqttService.connect({username: 'foo', password: 'bar'});
  }
}

export const MQTT_SERVICE_OPTIONS = {
  connectOnCreate: false,
  hostname: 'localhost',
  port: 1884,
  protocol: 'ws',
  path: '/mqtt'
};

export function mqttServiceFactory() {
  return new MqttService(MQTT_SERVICE_OPTIONS);
}

@NgModule({
  imports: [
    MqttModule.forRoot({
      provide: MqttService,
      useFactory: mqttServiceFactory
    })
  ],
  …
})

export class DemoModule { }
```

Does this help?

**Comment by hsmptg** [comment]
Hi
Sorry to dig up this closed issue but I presume that the solution proposed here is not possible right now since forRoot do not allow the argument provide for instance, since I get the following error:
_Argument of type '{ provide: typeof MqttService; useFactory: () => MqttService; }' is not assignable to parameter of type 'IMqttServiceOptions'. Object literal may only specify known properties, and 'provide' does not exist in type 'IMqttServiceOptions'._

Could you please provide a solution for the current version of ngx-mqtt?
Best Regards

**Comment by sclausen** [comment]
@hsmptg the error message actually describes the issue pretty well. The signature of `forRoot` isn't the same as 2017 anymore and doesn't accept a `provide` nor `useFactory` anymore, but a plain configuration object satisfying `IMqttServiceOptions`.
If you use the example from https://sclausen.github.io/ngx-mqtt/ and use the manual connection part of this example, you should be fine.
