### ISSUE TITLE
node_modules\mqtt\mqtt.js Unexpected character '#'  with webpack

### ISSUE THREAD

**Issue by Qowy** [sclausen/ngx-mqtt#44]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[X] Documentation issue or request
</code></pre>

What do I need to do to make this work with webpack and Angular 4?

Currently webpack throws an error on publish `node_modules\mqtt\mqtt.js Unexpected character '#' ` presumably because that is actually a node js file and not a client library.

**Comment by sclausen** [comment]
I don't know, what you've done. Could you provide a setup?
If you use it with angular-cli, which uses webpack to compile, it works like a charm for me, so if you could provide more information, ideally a repository with a reproducable error, I might be able to help you.

**Comment by Qowy** [comment]
Ok I am using the SPA templates from ASP.NET core:

`dotnet new angular`

After that I add ngx-mqtt to my package.json and it works fine for development.

However when I want to publish my application via `dotnet publish -c Release` for example I get the aforementioned error during webpack execution.
What dotnet does is the following:

```
<Exec Command="npm install" />
    <Exec Command="node node_modules/webpack/bin/webpack.js --config webpack.config.vendor.js --env.prod" />
    <Exec Command="node node_modules/webpack/bin/webpack.js --env.prod" />
```

Those two files should be the ones from this repository:
https://github.com/aspnet/templating/blob/dev/src/Microsoft.DotNet.Web.Spa.ProjectTemplates/content/Angular-CSharp/webpack.config.js
https://github.com/aspnet/templating/blob/dev/src/Microsoft.DotNet.Web.Spa.ProjectTemplates/content/Angular-CSharp/webpack.config.vendor.js

Since I am not too familiar with the whole webpack configuration I can't seem to find what I would have to change there.

I know that mqtt.js states in their documentation that one should run `webpack mqtt.js ./browserMqtt.js --output-library mqtt` in order to use it with webpack. And if I do this and manually rename browserMqtt.js to mqtt.js (replacing it) it works.
But is this the right solution? And if so how would I add this to my webpack.config

**Comment by sclausen** [comment]
Thank you very much for the detailed explanation of what you tried. Unfortunately, I don't use ASP.NET core at all, since I'm working on linux so I can't reproduce this.

The thing is, that with installing ngx-mqtt via npm, you don't need to compile mqtt.js code at all, since you already installed the built module where mqtt.js is included. mqtt.js is added to node_modules though, but I don't know why your webpack config tries to compile it.

The `#` in `node_modules/mqtt/mqtt.js` is indeed at the start of the file:

``` javascript
#!/usr/bin/env node
'use strict'
…
```
But I can't wrap my head around, why your webpack config tries to compile it.

I just made a new version where I moved mqtt.js where it belongs (to the devDependencies), so it won't be added to your node_modules.
Does this help with your issue?

**Comment by Qowy** [comment]
Thank you, I will try. Btw ASP.NET core works with Linux without problems so that is no excuse ;)

Another possibility may be that my webpack config tries to compile it like a TypeScript file or something. (Or maybe it is simply trying to transpile it to ES5 or something)

**Comment by Qowy** [comment]
Ok version 1.15.0 breaks it completely. I think this is to be expected, since your code actually depends on mqtt.js at runtime.

You do `import * as MQTT from 'mqtt';` in several files which results in `Module not found : error : Can't resolve 'mqtt'`.

However you also import angular stuff and that works so I am not really shure what  is going on here

I could try to use your minified version (which should have no dependencies) but as far as I know webpack is supposed to use the raw code and pack it itself.

What I am wondering is how this works for you, since you are also using webpack :)

But I think at this point this is more of a webpack question than your specific library

**Comment by sclausen** [comment]
You are supposed to use only the bundle. It's defined in the package.json of my module `"main": "bundles/ngx-mqtt.min.js",` which I thought would be picked up by your webpack configuration. Everything is already compiled into the bundle including mqtt.js.

**Comment by sclausen** [comment]
When I think about it, `1.15.0` was a mistake. `mqtt.js` belongs to the dependencies, not devDependencies, since it is possible (but not recommended) to don't use the bundle but the compiled js files. In this case, you indeed have to to compile mqtt.js for the browser for yourself, but that's out of my scope how you do it.

So I'll make a `1.16.0` back with `mqtt.js` as a dependency and would like to suggest you to use the bundle.

**Comment by Qowy** [comment]
ok thank you for your effort (and the great library in general). I agree that this is no longer your problem ;)
